import type { CommonContent } from "@/content/types";

export const common: CommonContent = {
  meta: {
    siteName: "ARASTE CAPITAL",
    defaultDescription:
      "Conseil indépendant en financements professionnels : financements relais, refinancements et dossiers complexes, côté emprunteur.",
  },
  nav: {
    firm: "Le cabinet",
    expertises: "Expertises",
    approach: "Notre approche",
    guides: "Repères",
    partners: "Partenaires",
    contact: "Contact",
    present: "Présenter une opération",
    menuOpen: "Ouvrir le menu",
    menuClose: "Fermer le menu",
    menuLabel: "Navigation principale",
    menuTitle: "Menu",
    skipToContent: "Aller au contenu",
    home: "ARASTE CAPITAL — accueil",
  },
  locale: {
    switchLabel: "Choix de la langue",
    current: "Langue actuelle",
    fr: "Français",
    en: "English",
  },
  footer: {
    navigationTitle: "Navigation",
    expertisesTitle: "Expertises",
    contactTitle: "Contact",
    legalTitle: "Informations",
    languagesTitle: "Langue",
    legal: "Mentions légales",
    privacy: "Confidentialité",
    contactPending: "Coordonnées à renseigner avant publication.",
    rights: "Tous droits réservés.",
    previewNotice:
      "Version de préproduction. Identité juridique, coordonnées et mentions réglementaires à confirmer avant publication.",
    tagline: "Conseil indépendant en financements professionnels",
  },
  ui: {
    allExpertises: "Toutes les expertises",
    allGuides: "Tous les repères",
    breadcrumbLabel: "Fil d'Ariane",
    homeCrumb: "Accueil",
    contents: "Sommaire",
    keyPoints: "À retenir",
    relatedExpertises: "Expertises liées",
    relatedGuides: "Pour aller plus loin",
    faq: "Questions fréquentes",
    readingTime: "{minutes} min de lecture",
    mobileCta: "Présenter une opération",
    presence: "Présence",
    localTime: "Heure locale",
    addressPending: "Adresse à renseigner avant publication.",
  },
  notFound: {
    title: "Cette page n'existe pas.",
    body: "L'adresse demandée est introuvable ou a changé. Vous pouvez revenir à l'accueil ou consulter nos expertises.",
    cta: "Retour à l'accueil",
  },
  error: {
    eyebrow: "Erreur",
    title: "Une erreur est survenue.",
    body: "La page n'a pas pu être affichée. Vous pouvez réessayer ou revenir à l'accueil.",
    retry: "Réessayer",
    home: "Retour à l'accueil",
  },
  loading: "Chargement",
};
