import type { CommonContent } from "@/content/types";

export const common: CommonContent = {
  meta: {
    siteName: "ARASTE CAPITAL",
    defaultDescription:
      "Independent financing advisory: bridge finance, refinancing and complex transactions for professional borrowers.",
  },
  nav: {
    firm: "The firm",
    expertises: "Expertise",
    approach: "Our approach",
    guides: "Guides",
    partners: "Partners",
    contact: "Contact",
    present: "Present a transaction",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    menuLabel: "Main navigation",
    menuTitle: "Menu",
    skipToContent: "Skip to content",
    home: "ARASTE CAPITAL — home",
  },
  locale: {
    switchLabel: "Language",
    current: "Current language",
    fr: "Français",
    en: "English",
  },
  footer: {
    navigationTitle: "Navigation",
    expertisesTitle: "Expertise",
    contactTitle: "Contact",
    legalTitle: "Information",
    languagesTitle: "Language",
    legal: "Legal notice",
    privacy: "Privacy",
    contactPending: "Contact details to be confirmed before publication.",
    rights: "All rights reserved.",
    previewNotice:
      "Pre-production version. Legal identity, contact details and regulatory statements to be confirmed before publication.",
    tagline: "Independent Financing Advisory",
  },
  ui: {
    allExpertises: "All areas of expertise",
    allGuides: "All guides",
    breadcrumbLabel: "Breadcrumb",
    homeCrumb: "Home",
    contents: "Contents",
    keyPoints: "Key points",
    relatedExpertises: "Related expertise",
    relatedGuides: "Further reading",
    faq: "Frequently asked questions",
    readingTime: "{minutes} min read",
    mobileCta: "Present a transaction",
    presence: "Presence",
    localTime: "Local time",
    addressPending: "Address to be confirmed before publication.",
  },
  notFound: {
    title: "This page does not exist.",
    body: "The requested address could not be found or has changed. You can return to the home page or browse our areas of expertise.",
    cta: "Back to home",
  },
  error: {
    eyebrow: "Error",
    title: "Something went wrong.",
    body: "The page could not be displayed. You can try again or return to the home page.",
    retry: "Try again",
    home: "Back to home",
  },
  loading: "Loading",
};
